name: .NET Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Merger.sln

    - name: Build for Linux
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.VERSION }} Merger.sln

    - name: Publish for Linux
      run: dotnet publish -c Release --os linux -o publish/linux /p:Version=${{ env.VERSION }} Merger.sln
      
    - name: Build for Windows
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.VERSION }} Merger.sln

    - name: Publish for Windows
      run: dotnet publish -c Release --os win -o publish/win /p:Version=${{ env.VERSION }} Merger.sln

    - name: Build for macOS
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.VERSION }} Merger.sln

    - name: Publish for macOS
      run: dotnet publish -c Release --os osx-x64 -o publish/osx /p:Version=${{ env.VERSION }} Merger.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build
        path: |
          publish/linux
          publish/win
          publish/osx

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')  # Runs only on tag push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-build
        path: publish

    - name: Archive Release
      run: zip -r release.zip publish

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
