name: .NET Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract Version from Tag
      id: get_version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "VERSION=0.0.1" >> $GITHUB_ENV  # Default version for non-tag builds
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore Merger.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.VERSION }} Merger.sln

    - name: Publish
      run: dotnet publish -c Release /p:Version=${{ env.VERSION }} Merger.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build
        path: publish

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')  # Runs only on tag push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-build
        path: publish

    - name: Archive Release
      run: zip -r release.zip publish

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
