name: .NET Build and Release

on:
  push:
    branches: [ "main" ]
    tags: ["*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore .\Merger.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore .\Merger.sln

    - name: Publish
      run: dotnet publish -c Release -o publish .\Merger.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build
        path: publish

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Only run on version tags
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-build
        path: publish

    - name: Archive Release
      run: zip -r release.zip publish

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
